spec:
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 512Mi
            limits:
              cpu: "1.0"
              memory: 1Gi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"tomcat":{"max-threads":1}}}'
          - name: AMQP_HOST
            value: broker-amq-amqp